### ISSUE TITLE
Support nodejs pipelines

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#103]
We should support nodejs (javascript) as language for gaia pipelines.

**Comment by greg-benner-klick-sensei** [comment]
JS ftw

**Comment by davojan** [comment]
Please implement it in typescript
You'll get much better and maintainable code and type definitions for typescript users for free :)

**Comment by ziras** [comment]
[README](https://github.com/gaia-pipeline/gaia#motivation):

> We believe it's time to remove all those abstractions and come back to our roots. Are you tired of writing endless lines of YAML-code? **Are you sick of spending days forced to write in a language that does not suit you and is not fun at all? Do you enjoy programming in a language you like?** Then Gaia is for you.

Based on this, typescript support and javascript support should probably be considered separate. I'd suggest create a ticket for typescript support in this case.

**Comment by davojan** [comment]
@ziras implementation written in typescript gives JS-support for free, users will not even notice that this is implemented in typescript. So it will kill two birds with one stone :)

**Comment by ziras** [comment]
@davojan That's a good clarification. Thanks!

**Comment by michelvocks** [comment]
Fixed by #183
