### ISSUE TITLE
Implement pipeline scheduling via cron syntax

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#105]
A good library to start with could be: https://godoc.org/github.com/robfig/cron

**Comment by Skarlso** [comment]
Starting working on this.

**Comment by michelvocks** [comment]
Hey @Skarlso . What is the status here? I would like to pick this one up if you don't mind. 😄

**Comment by Skarlso** [comment]
@michelvocks So sorry dude, I have my hands full with the Go PRs plus December is AOC month. :D Usually get nothing else done. :D

This is up for grabs yeah. I started working on it and hacked something together but wasn't really satisfied. And I was keeping in mind the work of #107. Which makes scheduling a bit harder. 🤔
