### ISSUE TITLE
Triggering builds in quick succession results in duplicated IDs

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#108]
<img width="1462" alt="screen shot 2018-09-21 at 11 46 54 am" src="https://user-images.githubusercontent.com/182850/45874074-3d890700-bd94-11e8-9f65-42230782b43c.png">

**Comment by michelvocks** [comment]
Uhm. That's pretty bad. The IDs are generated by boltDB as far as I can remember. I will check that.
Thanks for the report @Skarlso  🤗

**Comment by Skarlso** [comment]
@michelvocks No probs. I have a hunch that it might be only on the front-end. I didn't have the time to investigate deeper yet. That would be the best possible outcome... :) If it's deeper that's shait. We'd have to implement locking. :/

**Comment by Skarlso** [comment]
Unfortunately it's boltdb.
<img width="720" alt="screen shot 2018-09-24 at 06 39 44" src="https://user-images.githubusercontent.com/182850/45937848-aa82e380-bfc4-11e8-82bb-23b3cfd8ff95.png">

**Comment by Skarlso** [comment]
Aha, I see what's going on. I'll fix this.

**Comment by Skarlso** [comment]
Fixed
