### ISSUE TITLE
Gaia baseURL configuration for proxy support

### ISSUE THREAD

**Issue by KThornley** [gaia-pipeline/gaia#124]
I am currently looking at implementing Gaia in my K8 cluster alongside other DevOps tooling.  To integrate it with my ingress proxy I would like to be able to serve gaia under a sub directory e.g. /pipeline/...

Current configuration does not allow me to specific the baseURL

**Comment by thornleyk** [comment]
Difficulty comes with html content which directs itself back or serves itself from /, e.g. assets. Most proxys wont intercept this traffic and rewrite the html before delivery. Other monitoring toold e.g. grafana provide this capability

**Comment by thornleyk** [comment]
http://docs.grafana.org/installation/behind_proxy/

**Comment by KThornley** [comment]
Jaeger also had an issue regards this which we could consider https://github.com/jaegertracing/jaeger-ui/issues/42

**Comment by Skarlso** [comment]
I see. Carry on then.
