### ISSUE TITLE
[Documentation] Write up a developer setup / guide in order for people to get started

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#13]

**Comment by michelvocks** [comment]
Yes. We totally need that!

I'm currently working on a separate website just for documentation. 
You can find the repository here: https://github.com/gaia-pipeline/docs
Currently it's empty but I hope the first version will be available in a few days.

**Comment by marciorf** [comment]
Hello, any news on the doc?

Im interest in getting started with gaia, but Im a bit lost

**Comment by Skarlso** [comment]
@marciorf What do you need? Is there anything specific that is missing in order to develop gaia when looking at this document? https://github.com/gaia-pipeline/docs
