### ISSUE TITLE
Make Gaia work with go modules

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#145]
@michelvocks What do you think?  :)

**Comment by michelvocks** [comment]
@Skarlso yeah absolutely! 
To be honest, I still didn't had a look at go modules. 😿

**Comment by Skarlso** [comment]
@michelvocks To be honest, modules would make vendoring obsolete as to everyone who does a `go get` will have the specific module that Gaia requires to the hash. So we can be sure that the right dependencies will be used. 

That said, we can keep the vendor folder with `-mod=vendor` applied to `go build` for example and the rest of the commands. Do you prefer keeping the vendor folder? It would make new PRs a lot smaller if removed, since we don't have to update vendoring if a new dependency is introduced.

**Comment by michelvocks** [comment]
> Do you prefer keeping the vendor folder? It would make new PRs a lot smaller if removed, since we don't have to update vendoring if a new dependency is introduced.

That's a dope point in my opinion. Let's remove it 😄
