### ISSUE TITLE
[Question] Can i trigger build via API?

### ISSUE THREAD

**Issue by leberknecht** [gaia-pipeline/gaia#147]
Ahoi!

I couldnt find it on the docs, maybe i just missed it, but is it actually possible to trigger the builds/jobs via an API or something? In my use case, i need the build to run whenever a file is upload to a bucket on gcloud. I can hook the event with a cloud function, but not sure how to trigger execution then.

**Comment by Skarlso** [comment]
@leberknecht hi. The API is strongly protected with JWT and such. If you can authenticate a cli client, then yes, sure. :) The endpoints are available the admin is just a frontend for it.

**Comment by leberknecht** [comment]
Cool thing!
...Can you point me to documentation for the API or alike? :)

**Comment by leberknecht** [comment]
Ah sorry, missed the last part somehow.. so for the logs:

```
curl 'http://host:8083/api/v1/pipeline/1/start' -X POST -H 'Authorization: Bearer <JWT>' 
```
did the trick
