### ISSUE TITLE
java example

### ISSUE THREAD

**Issue by timchenxiaoyu** [gaia-pipeline/gaia#15]
please  offer java（mvn） example  ，thanks

**Comment by michelvocks** [comment]
Hello @timchenxiaoyu. Happy that you are interested in gaia. :hugs:

Sadly, gaia is in alpha phase and we currently only support pipelines written in go. :disappointed_relieved:
I hope that we can very soon support other programming languages too. Especially java is on the top-list. 

Please let me know when you have other questions.

**Comment by michelvocks** [comment]
Java is now officially supported. Docs are available here: https://docs.gaia-pipeline.io/develop-pipelines/java/
