### ISSUE TITLE
Make a pipeline triggerable more easily

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#151]
Add a token to a pipeline when it's created and display that token on the screen so it can easily be triggered through an api that doesn't require tedious authentication.

**Comment by Skarlso** [comment]
Going to start on this.

**Comment by Skarlso** [comment]
Uh I just realised that also means that the parameters would have to be passed along via a json body.

Like if your job has parameters that you need to set when it's running. Must also be considered. Trigger with parameters if you will

**Comment by michelvocks** [comment]
> @michelvocks so in order for this to work we need a non guess able token and add a user who has a another token. I think the two token thing is because it wants to be secure enough so people can't brute force a random job though an exposed public interface.
> 
> To that point the interface isn't even public. It's behhind a basic auth with a generated token.
> 
> Thuse you'd need to brute force two large tokens which just isn't worth the effort.

Right. We just need to make it easy to generate those two tokens. We already using token generation for UUID. I'm not quite sure but this shouldn't be guessable, right? 

> Like if your job has parameters that you need to set when it's running. Must also be considered. Trigger with parameters if you will

Uh, yeah, true. This is quite important too.

**Comment by Skarlso** [comment]
This was addressed by https://github.com/gaia-pipeline/gaia/pull/158
