### ISSUE TITLE
[Test] Create a small repo containing a README under gaia-pipeline.

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#16]
This will help shorten `git_test.go` by at least 5-7 seconds.

**Comment by Skarlso** [comment]
Actually, also have a main.go :) Which will return something like, Ok. As an output for further testing of the building process.

**Comment by michelvocks** [comment]
Thanks for reminding. I already forgot that. :smile:
Let me know if something is still missing.

https://github.com/gaia-pipeline/go-test-example

**Comment by Skarlso** [comment]
Perfect. Instead of 8 seconds now it runs in 1 second. :P
