### ISSUE TITLE
Use GCM for encryption in Vault

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#177]

**Comment by Skarlso** [comment]
GCM is authenticated but suffers from other things. It would make the encryption part a lot easier without needing padding. However it requires a randomised nonce and for that, we must consider properly maintaining a counter to avoid the birthday bound of random nonces problem.

**Comment by Skarlso** [comment]
This is a bit harder than it first looks. GCM is awesome, but where we store the counter for the unique IV is not trivial at all.

I have yet to see a nice enough implementation of AES-GCM-SIV and I don't think storing the counter in the DB is good. Because if the db gets wiped but the vault does not, the counter will reset to 0 which is bad because it will generate a non-unique value for the same key.

**Comment by michelvocks** [comment]
Hey @Skarlso 
What is the use case here?

**Comment by Skarlso** [comment]
GCM would provide an increased encryption security and also, as an added bonus, authentication. That means that we would have a way to detect tempering with the vault file. The decryption simply wouldn't work if the file has been tempered with.

The problem is that using random IVs as I'm doing it now, is not feasible with GCM. It will repeat itself after 2^32 uses of random nonces with the same key. Currently we are using the certificate as key so that would be possible since the key never changes.

AES + CFB right now is fine... but using GCM would make the encryption a lot simpler. In fact it would only be a few lines of code since GCM has been implemented in Go nicely here: https://golang.org/pkg/crypto/cipher/#NewGCM

The problem is that it needs a counter. This counter is used in order to make the IV unique for each encryption. But how to deal with the counter is difficult... :/

**Comment by Skarlso** [comment]
In short.. increased security, decreased complexity. Given I can solve the counter issue.

**Comment by michelvocks** [comment]
Cool. HashiCorp Vault uses AES + GCM: 

> The security barrier automatically encrypts all data leaving Vault using a 256-bit Advanced Encryption Standard (AES) cipher in the Galois Counter Mode (GCM) with 96-bit nonces.

Maybe we can have a look there how it is implemented?

**Comment by Skarlso** [comment]
@michelvocks https://github.com/hashicorp/vault/blob/ebc733f4ca5d362fdfb302ac75953228585c54a2/vault/seal/envelope.go#L34

Bad Hashicorp. :( bad. :(

**Comment by Skarlso** [comment]
@michelvocks https://github.com/hashicorp/vault/blob/e9256ed4775a5cf517a3aa71f148ce4d50ef2b42/vault/barrier_aes_gcm.go#L839

I'm disappointed. Can you fix this? :D

**Comment by Skarlso** [comment]
@michelvocks Ok. I've talked to some people and re-read the RFC here: https://tools.ietf.org/html/rfc5288#section-3

The counter can be a known value. The cipher must be a secret though. Having it derived from the certificate might be a problem 🤔 But I will ponder that later.

**Comment by Skarlso** [comment]
On of the options I'm thinking of is upon starting Gaia, the user has to unlock the vault or enter a password for the vault.

Once Gaia is running the vault can be accessed without the need of entering a password.

However, that means we'd store the password in memory. Arguably that's way better than storing it on the file system like the certificate. But would increase the trouble a person has to go through when starting up Gaia. Unless I make it a configurable environment property. Which is also shit. :D But still better than the filesystem. What do you think @michelvocks? 

The vault than would look something like this: `<counter>||IV||<encrypted_data>`.

**Comment by Skarlso** [comment]
While thinking about this, one thing that came to mind is that this would break backwards compatibility. Gaia would no longer start unless you have this property defined.

I could auto-generate one, but that would get lost on the first re-start making the second start fail to decrypt the vault.

**Comment by michelvocks** [comment]
I really like how you are thinking but in my opinion we are reinventing Vault then and, like you already said, it is not really user-friendly.

If you really need this kind of security, I would recommend to store credentials in HashiCorp Vault and get credentials on the fly during pipeline execution. That doesn't mean that I don't like GCM, I still think we should switch to GCM but maybe use a "less secure" approach here e.g. store secret on filesystem.

**Comment by Skarlso** [comment]
Okay. 👍 :) True. I'll use GCM and still use the certificate. I'll think of something later. Maybe store it next to the vault. :)

**Comment by Skarlso** [comment]
Closed by #178
