### ISSUE TITLE
https://golangci.com/

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#179]
@michelvocks Dude!!!

**Comment by Skarlso** [comment]
Does reports like this:
<img width="888" alt="screenshot 2019-03-08 at 13 57 20" src="https://user-images.githubusercontent.com/182850/54029828-1b503d80-41aa-11e9-8c2b-f090948a24c5.png">

Line by line on a PR.

**Comment by michelvocks** [comment]
@Skarlso Cool. Let's try it 😄

**Comment by Skarlso** [comment]
Awesome! :D
