### ISSUE TITLE
Cannot access git repo: ssh: cannot decode encrypted private keys

### ISSUE THREAD

**Issue by DHunte** [gaia-pipeline/gaia#182]
Hi,

Im having issues with using the SSH key for my account. I followed the default guide [here](https://help.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account) which apparently outputs an encrypted private key that golang ssh does not support I believe?

Cannot access git repo: ssh: cannot decode encrypted private keys

Iv not seen any issues related to it in the issues sections so I thought it was worth posting, but it might have already been addressed.

**Comment by michelvocks** [comment]
Hi @DHunte,

thanks for your report! 

I assume that you try to pull pipeline code via Gaia from a private GitHub repository?
In theory, this should work. Did you try to add your SSH user and your password from your encrypted OpenSSH key? When you create a new pipeline, there is a button called `Add Credentials` which opens a popup. In this popup you need to click on `SSH Key`:

![Screenshot 2019-06-14 at 07 31 03](https://user-images.githubusercontent.com/2463119/59485594-b9713500-8e76-11e9-9e87-184086b8055e.png)

Please let me know if this solved your problem.

Cheers,
Michel

**Comment by DHunte** [comment]
Hi,

Thanks for the response but yes this is actually the screen previous to the one that displays the warnings :

Cannot access git repo: ssh: cannot decode encrypted private keys

This warning appears after I have entered the credentials, in red text below the git private url bar and after I have added the private ssh key, username and password. I have tried many times and tried various methods to generate the keys:

ssh-keygen -t rsa -b 4096 -C "my@email.com"
ssh-keygen -t rsa -b 2048 -C "my@email.com"

incase there is some fundamental difference but it doesent seem to resolve the issue.

**Comment by michelvocks** [comment]
Hi @DHunte,

I was able to reproduce your issue. 

The problem is that ssh-keygen now produces automatically a key in RFC4716-format. A few months ago, it was still the old "PEM" format. Go does not support SSH keys in the RFC4716-format. It does support keys in the PKCS#8 format but only unencrypted keys are supported currently.

The workaround, for now, is to generate a private key in the old PEM format e.g.:
`sh-keygen -t rsa -b 4096 -m PEM`

This will generate an RSA key with 4096 bits in the old PEM format.

Cheers,
Michel

**Comment by DHunte** [comment]
Awesome it works now, thanks for taking the time to investigate this issue. I think the issue is now closed as I can get it working but it seems that given the tutorial is the standard for github its maybe worth mentioning somewhere until go implements a fix?

**Comment by michelvocks** [comment]
@DHunte Yes, definitely. Please leave this issue open as a reminder for us 😄

**Comment by Skarlso** [comment]
@michelvocks You mean, this? https://godoc.org/golang.org/x/crypto/ssh#FingerprintLegacyMD5

**Comment by Skarlso** [comment]
Can't we use fingerprints? I have to check what's the concrete problem first and where. But usually, SSH only compares fingerprints since those are much smaller than the whole key.

And Go does support creating RFC4716 type fingerprints.

**Comment by Skarlso** [comment]
Yeah if I see correctly, we are trying to find the public keys for a user? I think we should be able to do that using fingerprints only.

**Comment by Skarlso** [comment]
Oh, I think it's actually go-git which needs to do something about this. Since that's who's SSH package we are using. We explicitly names the go-one `gossh`.

**Comment by Skarlso** [comment]
Here is the error origin btw: https://github.com/src-d/go-git/blob/master/plumbing/transport/ssh/auth_method.go#L126

**Comment by Skarlso** [comment]
Note, I filed a feature request to go-git.
https://github.com/src-d/go-git/issues/1171

**Comment by DHunte** [comment]
Thanks for taking a look into this issue and raising the error with gogit - but maybe it would be a useful feature to allow access-tokens for authentication. Some other event systems such as beehive https://github.com/muesli/beehive/ already have a git worker that authenticates using access tokens, it seems like a good alternative until the ssh issue is resolved?

**Comment by Skarlso** [comment]
@DHunte Either github is bugging, or I don't see your comment. I've got the email about it though. :) 

You can use the token in the password field in a regular checkout.
```
Username: your_username
Password: your_token
```

**Comment by Skarlso** [comment]
Hi @DHunte. Is this still a problem?

**Comment by DHunte** [comment]
Hi, sorry for the delay, this appears to be fixed now. Thanks!

**Comment by Skarlso** [comment]
Wonderful! Thanks!
