### ISSUE TITLE
strings.ReplaceAll is will not work on go version < 1.12

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#192]
@michelvocks Hey. Do we care about this? strings.ReplaceAll in workers/agent/agent.go is a new addition. It was Replace(new, old, -1) before. I'm not sure we care as we always strive to go ahead with the latest change, but as Go progresses and Gaia progresses we won't always be able to upgrade immediately.

Granted, replaceAll isn't working on go1.11 which is an older version. But it's still the default in some linux distributions.

What say you?

**Comment by michelvocks** [comment]
In my opinion, that's fine. The default go version might be below 1.12 for some linux distributions but they still can update manually if they really want to compile Gaia.
