### ISSUE TITLE
The nounce counter can potentially overflow

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#202]
If there are many many requests to the vault it's possible to overflow the integer nounce counter. I should fix that.

**Comment by Skarlso** [comment]
More precisely, if it gets above 18446744073709551615.

**Comment by michelvocks** [comment]
I assume the nounce counter is increased by one when a secret is stored?

**Comment by Skarlso** [comment]
Yep

**Comment by michelvocks** [comment]
Well... then I think it's fine 😄
