### ISSUE TITLE
Is server and worker mode fault tolerant?

### ISSUE THREAD

**Issue by everimbaq** [gaia-pipeline/gaia#208]
We are considering to use it to execute ci&cd pipeline. Is gaia server and worker fault tolerant? A local database dose not work well on high avaliablity . I read the source code and can't find docs about this. Thanks~

**Comment by Skarlso** [comment]
?

**Comment by Skarlso** [comment]
Hi @everimbaq. It is as fault tolerant as you make it. :)

The main master will choose workers based on availability. Pipelines will not be bound to a worker. Labels are used for that. Which means if, for example, you have a kubernetes deployment and your workers are pods and a worker is restarted / dies, the pipeline will just continue to work and schedule work on a different worker.

Now the master is a bit more interesting. If the master dies, you'll have a problem. But that's the same with Jenkins and all other master / worker relationship type of CI/CD solutions. However, restarting it will just keep it working as everything is stored. You can't have multiple masters operating on the same database or data. Each Gaia master works on its own.

**Comment by everimbaq** [comment]
Thanks for your detailed and clear description.

**Comment by Skarlso** [comment]
Oh and btw, if the master dies, the workers will keep trying to periodically contact it. And once the master comes back up, they will all just reconnect if it has the same address. No need to restart the workers.

Yw. :) Thank you for opening an issue!
