### ISSUE TITLE
Convert from make to mage

### ISSUE THREAD

**Issue by fubarhouse** [gaia-pipeline/gaia#22]
I understand there's not much to gain from this, but in the spirit of going native, I propose this project moves from Make to Mage.

[Mage](https://github.com/magefile/mage) is a native Go-based replacement where you can actually write real code for your make functions rather than scripting a series of shell commands.

More at https://github.com/magefile/mage

I would be prepared to produce most (if not all) of this work if you're interested.

**Comment by Skarlso** [comment]
So, if makefiles are just fancy bash scripts with some make syntax, then magefiles are fancy bash scripts with go syntax and code in between which makes it even harder to read between the lines of what it does. And essentially what it does is call binaries.

Like:

```go
func getDep() error {
	return sh.Run(goexe, "get", "-u", "github.com/golang/dep/cmd/dep")
}
```

Or:

```go
// Build hugo Docker container
func Docker() error {
	if err := docker("build", "-t", "hugo", "."); err != nil {
		return err
	}
	// yes ignore errors here
	docker("rm", "-f", "hugo-build")
	if err := docker("run", "--name", "hugo-build", "hugo ls /go/bin"); err != nil {
		return err
	}
	if err := docker("cp", "hugo-build:/go/bin/hugo", "."); err != nil {
		return err
	}
	return docker("rm", "hugo-build")
```

Which is a ton of fluff for essentially 3 commands. And I wouldn't want to see go's verbose error handling scheme embedded into a makefile for which the purpose is to keep it as simple as possible.

Now, granted, makefiles can be insanely cryptic no argument there. But I think on this project @michelvocks can keep it simple and pure. :)

This is my opinion to this matter, and please excuse me for chiming in here. :) Please feel free to ignore me.

**Comment by michelvocks** [comment]
I agree with @Skarlso. Make is supported out-of-the-box on linux and MacOS operating systems. We are (currently) using it for a few simple steps which are quite easy to understand. 
And they must be easy because I wrote them and I have no clue about makefiles. :smile:

I will close this for now but I will keep that in my mind if I see our makefile growing into something that is close to a nightmare. :skull:
Thanks a lot for your feedback! Always appreciated. 🤗
