### ISSUE TITLE
Does gaia support Python3？

### ISSUE THREAD

**Issue by leafonsword** [gaia-pipeline/gaia#230]
From doc https://docs.gaia-pipeline.io/develop-pipelines/python/ , gaia supports Python2.7, does gaia support python3?

**Comment by Skarlso** [comment]
hi! Thanks for opening an issue. A PR is already present in the Python SDK to support 3.
https://github.com/gaia-pipeline/pythonsdk/pull/1

**Comment by leafonsword** [comment]
@Skarlso Thanks for replying, hope Python3 supporting PR could be merged soon~

**Comment by Skarlso** [comment]
Ping @michelvocks with that. :))))

**Comment by prologic** [comment]
Technically you just need to implement the gRPC protocol; So even without  the "official language X" PR merged you could just write against the protocol :) Just say'n!
