### ISSUE TITLE
Cannot access git repo: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by hzgcoding** [gaia-pipeline/gaia#232]
![image](https://user-images.githubusercontent.com/8913042/71500072-58530100-289e-11ea-9e6d-242cdc6a2f37.png)

![image](https://user-images.githubusercontent.com/8913042/71500091-6f91ee80-289e-11ea-840a-c53ef13f286a.png)

Cannot access git repo: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

please help me !!!

**Comment by Skarlso** [comment]
Hi, this seems to be related to https://github.com/gaia-pipeline/gaia/issues/182 ?

**Comment by hzgcoding** [comment]
> Hi, this seems to be related to #182 ?

this is different thing!

my project   is used  in gitlab

**Comment by michelvocks** [comment]
Hi @hzgcoding!

This is not related to the git provider you use but more related to the format of your private-public key format. Please see the following message for more information: https://github.com/gaia-pipeline/gaia/issues/182#issuecomment-502120516

Could you provide more information about the way you generated your private-public key pair? What ssh-keygen version do you use? Have you tried to generate a new key pair with the command I mentioned in my post? 

Cheers,
Michel

**Comment by hzgcoding** [comment]
> Hi @hzgcoding!
> 
> This is not related to the git provider you use but more related to the format of your private-public key format. Please see the following message for more information: [#182 (comment)](https://github.com/gaia-pipeline/gaia/issues/182#issuecomment-502120516)
> 
> Could you provide more information about the way you generated your private-public key pair? What ssh-keygen version do you use? Have you tried to generate a new key pair with the command I mentioned in my post?
> 
> Cheers,
> Michel

use 'ssh-keygen'  cmd 
~$ ssh -V
OpenSSH_7.4p1 Debian-10+deb9u4, OpenSSL 1.0.2l  25 May 2017

And I try it [https://github.com/gaia-pipeline/gaia/issues/182#issuecomment-502120516](182) but it not work , the thing is still here

Retry above step but not work...
