### ISSUE TITLE
Integration with Gitea

### ISSUE THREAD

**Issue by X-Ryl669** [gaia-pipeline/gaia#249]
Thanks for your code. It's very good.

I was wondering how can I integrate it with Gitea's webhook ?
(Said differently, how can I trigger a pipeline from outside the admin interface via a HTTP call ?)

**Comment by Skarlso** [comment]
You can do that with the pipeline remote trigger action.

If you access your pipeline, you'll see a trigger token like this:

<img width="1628" alt="Screenshot 2020-05-26 at 9 44 13" src="https://user-images.githubusercontent.com/182850/82873877-7730ee80-9f35-11ea-8cd3-8e7de3ff1ca9.png">

Use that to trigger a pipeline by calling the rest endpoint without the need for an authenticated client like this:

```
curl -X POST http://localhost:8080/api/v1/pipeline/2/6ffb6acf-8438-5cd7-b819-0d18e9c47b68/trigger
```

**Comment by Skarlso** [comment]
Uh, that was actually not working correctly. :/ Bummer.

Here is the fix: https://github.com/gaia-pipeline/gaia/pull/251

But I'm afraid that it will not be released any time soon.... so you'll have to build your own gaia to make it work....

**Comment by Skarlso** [comment]
This has been fixed and released.

**Comment by X-Ryl669** [comment]
Indeed, it's working with the trigger URL.

**Comment by Skarlso** [comment]
Yay!
