### ISSUE TITLE
Question: RSS Feed polling as trigger?

### ISSUE THREAD

**Issue by issmirnov** [gaia-pipeline/gaia#264]
Hi all,

I'm evaluating whether gaia solves the following use case:
1. github release emitted on https://github.com/go-gitea/gitea/releases
2. This triggers a custom job that runs an ansible playbook to deploy this release everwhere.

I also already have an IFTTT recipe that emails me new releases, so I could have it hit a web hook as well.

What are the current options in GAIA for monitoring external resources and triggering jobs?

**Comment by Skarlso** [comment]
Hi @issmirnov! Thanks for evaluating Gaia!

Currently you can trigger a pipeline using a trigger token which doesn't have an auth requirement. Plus you can have webhooks on repos but only on push events. So right now there are no custom events that gaia can listen on I'm afraid. That said, do you only need other event types from github?

**Comment by issmirnov** [comment]
Hey @Skarlso 

Thanks for getting back to me! Apologies about late reply, email got burried. 

For my use case, yes, I just want to be notified when there's a new Gitea release here on github. I'll keep looking for tools! Perhaps a self-hosted Zapier clone or something would work. Recs welcome, should you have some :)

**Comment by Skarlso** [comment]
No problem!

For these things honestly, I just create my own bot and run it somewhere. :) It's pretty easy to listen on a github release event.

In fact, I'm just writing a bot for Gaia right now here [Gaia Bot](https://github.com/gaia-pipeline/gaia-bot) if you want some inspiration on how to do it. :)

Good luck!
