### ISSUE TITLE
gaia compile 

### ISSUE THREAD

**Issue by anborg** [gaia-pipeline/gaia#291]
I couldn't compile frontend. Where can I find steps to compile ?

At root

```
go build

go: downloading github.com/hashicorp/go-hclog v0.0.0-20180709165350-ff2cf002a8dd
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/robfig/cron v0.0.0-20180505203441-b41be1df6967
```

cd frontend
yarn install
yarn serve
```log
 frontend % yarn serve
yarn run v1.22.4
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                         5:59:35 PM

 error  in ./src/store/modules/menu/lazyLoading.js

Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting /Volumes/data01/projects/projects_go/gaia/frontend/src/store/modules/menu/lazyLoading.js:3
    at SourceCode.getTokenBefore (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at /Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/util/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at /Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/linter.js:752:32
    at Array.forEach (<anonymous>)
    at runRules (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/linter.js:747:15)
    at Linter._verifyWithoutProcessors (/Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/linter.js:899:31)
    at /Volumes/data01/projects/projects_go/gaia/frontend/node_modules/eslint/lib/linter.js:955:35
    at Array.map (<anonymous>)

 @ ./src/router/index.js 5:0-60 22:15-26 26:15-26 30:15-26
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.199:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

```

**Comment by Skarlso** [comment]
Hi @anborg 

That looks like some kind of version thing... Frigging node. :) I'll take a look.

What are you trying to do? I usually run `npm run serve` or if you would like to create a production install then run `make compile_frontend` from the root which does this:

```
compile_frontend:
	cd ./frontend && \
	rm -rf dist && \
	npm install && \
	npm run build
```

Meaning we usually don't use `yarn`.

**Comment by Skarlso** [comment]
Hi @anborg 
Is still an issue for you?

Cheers

**Comment by anborg** [comment]
Hi @Skarlso, 

Sorry I almost forgot what I did... 

**The frontend is compiled and started** 

```sh
cd ./frontend && \
	rm -rf dist && \
	npm install && \
npm run serve
```

**The backend seem to have problem starting.**

```sh
/Volumes/data01/projects/project-experts/gaia/cmd/gaia
go build
 ls
gaia	main.go
./gaia
2020-12-13T00:51:25.654-0500 [DEBUG] Gaia: executeable path found: path=/Volumes/data01/projects/project-experts/gaia/cmd/gaia
2020-12-13T00:51:26.177-0500 [WARN ] Gaia: using auto-generated key to sign jwt tokens, do not use in production
2020-12-13T00:51:26.177-0500 [INFO ] Gaia: vault file doesn't exist. creating...
2020-12-13T00:51:26.178-0500 [INFO ] Gaia: the vault is empty
2020-12-13T00:51:26.178-0500 [INFO ] Gaia: global worker registration secret has not been generated yet. Will generate it now...
2020-12-13T00:51:26.178-0500 [INFO ] Gaia: rbac enabled: false
2020-12-13T00:51:26.178-0500 [INFO ] Gaia: rbac disabled
2020-12-13T00:51:26.179-0500 [ERROR] Gaia: Cannot find assets in production mode.
2020-12-13T00:51:26.179-0500 [ERROR] Gaia: cannot initialize handlers: error="could not locate box "../frontend/dist""

```

Perhaps I'm starting from wrong directory? 
Would be great if you could provide list of commands to run from root gaia directory

**These frontend errors are likely due to backend errors**

```log
 App running at:
  - Local:   http://localhost:8081/ 
  - Network: http://192.168.0.137:8081/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

Proxy error: Could not proxy request /api/v1/login from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/v1/login from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/v1/login from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/v1/login from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/v1/login from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).


```

**Comment by Skarlso** [comment]
Indeed. You need to build from root. There is a Makefile so if you have make then simply run `make` to run in dev mode. Otherwise there is another command to run in prod I have to look up. I'm on the phone.

**Comment by Skarlso** [comment]
So, if you want a prod release, you run the following commands:

```
make release
```

This will create the single binary which will have all the components in it, and that you can run now from anywhere you like.

**Comment by Skarlso** [comment]
Oh and you need [rice](https://github.com/GeertJohan/go.rice) installed somewhere on your PATH.

**Comment by anborg** [comment]
This only creates a linux binary. Does it crate exe in windows, and mac executable?

```log
-rwxr-xr-x   1 mer  staff  42893312 Dec 27 14:05 gaia-linux-amd64
-rw-r--r--   1 mer  staff     11626 Dec 13 00:44 gaia.go
-rw-r--r--   1 mer  staff      3391 Dec 27 14:04 go.mod
-rw-r--r--   1 mer  staff     39316 Dec 27 14:04 go.sum
drwxr-xr-x  15 mer  staff       510 Dec 27 14:04 handlers
drwxr-xr-x   7 mer  staff       238 Dec 13 00:44 helm
drwxr-xr-x   7 mer  staff       238 Dec 13 00:44 helper
drwxr-xr-x   5 mer  staff       170 Dec 13 00:44 plugin
drwxr-xr-x   7 mer  staff       238 Dec 13 00:44 providers
drwxr-xr-x   9 mer  staff       306 Dec 13 00:44 screenshots
drwxr-xr-x  12 mer  staff       408 Dec 13 00:44 security
drwxr-xr-x   3 mer  staff       102 Dec 13 00:44 server
drwxr-xr-x   4 mer  staff       136 Dec 13 00:44 services
drwxr-xr-x   5 mer  staff       170 Dec 13 00:44 static
drwxr-xr-x  15 mer  staff       510 Dec 13 00:44 store
drwxr-xr-x   8 mer  staff       272 Dec 13 00:44 workers
mer@PKML01 gaia % ./gaia-linux-amd64 
zsh: exec format error: ./gaia-linux-amd64


```

**Comment by Skarlso** [comment]
Eek, sorry, you're right. That only creates a linux binary. We definitely should use gox to build for multiple platforms. :/

Luckily, now that you have everything else built, you just need to run this command:

```
go build $(GO_LDFLAGS_STATIC) -o gaia.exe ./cmd/gaia/main.go
```

which replaces the `compile_backend` part of the release process.

**Comment by anborg** [comment]
Since GO is multi platform, perhaps a separate Makefile config, that creates gaia.exe or gaia(mac),   for those who do not want to use docker-overhead. Automatically detecting the OS  - I believe GO supports such bulding.

**Comment by Skarlso** [comment]
Yep. It's called gox. :-)

**Comment by Skarlso** [comment]
I'll add [gox](https://github.com/mitchellh/gox) to the package which should build all supported binary types.

**Comment by Skarlso** [comment]
@anborg hi. If you use the attached pr I added gox to the mix. you have to install it, and after that if you run
`make binaries` it will create all the binaries. :)

So the steps would be:

```
# Install Gox

make compile_frontend
make static_assets
make binaries
```

This should now include all the things in all the binaries.

**Comment by anborg** [comment]
@Skarlso , thanks.. 

Is there a way to get it working on win? 

![image](https://user-images.githubusercontent.com/56970398/103296636-75944100-49c4-11eb-98bd-783985e3d666.png)

```log
C:\data\projects\projects_go\src\github.com\gaia-pipeline\gaia>make dev
go run ./cmd/gaia/main.go -home-path=/tmp -dev=true
2020-12-29T10:33:26.836-0500 [WARN ] Gaia: using auto-generated key to sign jwt tokens, do not use in production
2020-12-29T10:33:26.839-0500 [INFO ] Gaia: rbac enabled: false
2020-12-29T10:33:26.839-0500 [INFO ] Gaia: rbac disabled
2020-12-29T10:33:26.844-0500 [INFO ] Gaia: worker gRPC server about to start on port: 8989
⇨ http server started on [::]:8080
```

**Comment by Skarlso** [comment]
What are you trying to do? Gaia provides a rest api. Not a GRPC one. The GRPC api is the plugin's api. That's not intended to be used directly. If you are trying to use it without the frontend, I suggest to take a look at the swagger docs, which you can view if you started up the server by navigating to : http://localhost:8080/api/v1/swagger/index.html
You can then see what you can do.

Looking at the make command though, you are running under dev, which means you aren't running the frontend by default.
Navigate to the frontend folder, and run `npm run server` then navigate to http://localhost:8081 where the frontend lives.

**Comment by anborg** [comment]
Great thanks...


**Backend:**  
```sh
make dev
```
http://localhost:8080/api/v1/swagger/index.html



**Frontend:** 

```sh
cd frontend
npm run server
```
http://localhost:8081/#/overview

I can live happily without docker, in windows (though I wish to use linux).  
Will try different options
- saving state of server in a folder
- changing port for backendapi & frontend
- using Vault for storing pwd, db setting etc and 
- check if Consul can be used for storing config values, and use those in worker/action nodes in a pipeline?!
- figure out if "pipeline" topology can be saved / versioned as a file?!
- find if there is a way to see the overall status in a dasboard?!

**Comment by anborg** [comment]
How do I create a single binary that serves both api, and javascript-frontend, i.e no need to run two different commands? 

[Yes docker combines both BE&FE.  But, if I could just create a simple gaia-app.go which serves a fixed verson js-frontend, and the swagger, I can just drag drop that exe/binary anywhere and try different things ... ]

**Comment by Skarlso** [comment]
That's the process I outlined above. Build that frontend compile statics
then build the binary. That will serve all after that. It's a single binary
and the frontend is compiled into it. But then it needs a few things like
what's the serving path and such.

Hostname needs to be defined then 8080 should serve the frontend.

**Comment by Skarlso** [comment]
You don't even have to provide that. Just run the compiled binary of your chose and navigate to http://localhost:8080.

This will now contain the backend AND the frontend.

The steps are, without using `make release`:

```
make compile_frontend
make static_assets
make binaries # with the new branch ( which I'll merge soon )
```

**Comment by anborg** [comment]
Thank you

It took a bit of time to have 4 binaries. Additional time may not matter for my needs..
![image](https://user-images.githubusercontent.com/56970398/103370176-215b9080-4a9a-11eb-8012-9f97d731f10c.png)

**Comment by Skarlso** [comment]
Fair point. I added an override. You can now run this:

`make BINARIES=windows/amd64 binaries`

This will only build windows/amd64. You can define whatever you want in there, with a coma separated list. Look for an example in the Makefile.

**Comment by Skarlso** [comment]
Related pull: https://github.com/gaia-pipeline/gaia/pull/296
