### ISSUE TITLE
Modify, Delete Pipeline feature

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#30]
We already have a `Settings` subpage. We need a new tab-pane for managing pipelines. 
Maybe a table with all currently active pipelines and every entry has buttons/icons to modify (renaming) and removing this pipeline. 

What needs to be done:

1. Create the functionality in the backend.
2. Create a new tab-pane in the settings view with the required functionality.

**Comment by bidhan-a** [comment]
Hey @michelvocks I would like to take this on if you aren't working on it already. Please let me know!

**Comment by michelvocks** [comment]
Hey @bidhan-a 🤗 
Awesome! Really happy that you want to work on this! ❤️ 
Feel free to start and don't hesitate if you got questions or simply want feedback!
