### ISSUE TITLE
Unable to connect to GHE

### ISSUE THREAD

**Issue by RamuRChenchaiah** [gaia-pipeline/gaia#300]
Hi There
1. We have brought up Gaia Pipeline within our enterprise network.
2. Trying to create a piepline: Added ssh key & https url for our GHE. We get "Cannot access git repo: authorization failed" 
3. We tried using ssh url, got "Cannot access git repo: git url should not include username and/or password"

Would you please help on this connectivity to GHE?

Thank you

**Comment by Skarlso** [comment]
Hi. Thanks for your issue, I'll take a look later on. :)

**Comment by Skarlso** [comment]
I assume that gaia has Internet access and the repo is given with, ssh:// url?

**Comment by Skarlso** [comment]
I mean git@github. Also note that username and password are no longer supported by Github. So we might as well remove that feature.

**Comment by RamuRChenchaiah** [comment]
Refer: https://github.com/gaia-pipeline/gaia/issues/149
