### ISSUE TITLE
Consuming custom function from custom modules from the pipeline (__init__.py)

### ISSUE THREAD

**Issue by RamuRChenchaiah** [gaia-pipeline/gaia#305]
Dear Team

We placed custom code in different modules & tried to consume from __init__.py

To our surprise, the import fails with error 'No such module src'.
This is a refactored working code from development without inclusion of gaia-pipeline. when invoked from the pipeline code, it fails. 

Further debugging shows that the custom modules are not copied into /tmp/data/* folder location at all, the docker is started with volume mapping of current directory to /data.

May we know if we miss something here please?

Thank you

**Comment by Skarlso** [comment]
Hi @RamuRChenchaiah!

Did you find out what the problem was?
