### ISSUE TITLE
Scheduar is not picking up the execution

### ISSUE THREAD

**Issue by RamuRChenchaiah** [gaia-pipeline/gaia#307]
Hi There

We have setup our pipeline with schedule 0 0 6 * * * (following the provided link).
So far it is more than 8 hours, but the trigger does not happen.
We observed no logs on the same either.

Any help/pointers please?

Thank you

**Comment by RamuRChenchaiah** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/14149055/141230205-7136aa12-d743-4d68-a712-a70890123588.png">

**Comment by RamuRChenchaiah** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/14149055/141230272-b38993a7-b985-44fd-8771-cb6edcbb67e4.png">

**Comment by Skarlso** [comment]
Interesting, I think there is a setting where you have to enable crons if I recall correctly. 🤔 I'll take a look.

**Comment by Skarlso** [comment]
There is no setting, also I remember that the library we use is using an incorrect syntax for the crons. Try removing a zero and see if that does anything. :)

**Comment by RamuRChenchaiah** [comment]
@Skarlso 
Sure, Thanks. Let me check with that.

**Comment by RamuRChenchaiah** [comment]
Hi @Skarlso 

unfortunately, this did not work.
Any help please.

Thanks

**Comment by Skarlso** [comment]
Huh, odd. I'll check it then I'll get back to you shortly.

**Comment by Skarlso** [comment]
So I created a new pipeline using `1 * * * * *` and it does run every 1 minute:

<img width="1749" alt="Screenshot 2021-11-15 at 12 36 02" src="https://user-images.githubusercontent.com/182850/141775487-3f9554ce-104b-4dc3-a79d-57a7462d7707.png">

**Comment by Skarlso** [comment]
<img width="1776" alt="Screenshot 2021-11-15 at 12 37 16" src="https://user-images.githubusercontent.com/182850/141775604-d2a499f5-de6d-4920-a47f-95affd617b40.png">

Keeps on running nicely.

**Comment by RamuRChenchaiah** [comment]
Thanks, @Skarlso 
The 1min, 1hourly settings work.

Where we had problem is: 
After a while(not sure on the timeline), we see the pipeline moves to 'scheduled' state, and not moving to 'running' and the 'success' state.

**Comment by Skarlso** [comment]
Sadly, I have no idea. :( That scheduler is some old code, and I don't have the bandwidth to fully investigate what's going on there. I'll do my best effort to rummage through that and try to find out if there is something wrong.
