### ISSUE TITLE
White Labeling

### ISSUE THREAD

**Issue by RamuRChenchaiah** [gaia-pipeline/gaia#308]
Hi There

Would you please advice if there is a way to perform white label changes?
I checked the docs, I am afraid I got some.

Thanks

**Comment by Skarlso** [comment]
Hi @RamuRChenchaiah. Would you please explain what you mean by white labels?

**Comment by RamuRChenchaiah** [comment]
Hi @Skarlso 
Please  note that I am referring to customizing the logo, Site Title, Favicon etc.,
Not looking much on the UI changes but very minimal.

Thank you

**Comment by Skarlso** [comment]
Oh I see. :D Yeah I don't think we have that kind of thing. :D

**Comment by RamuRChenchaiah** [comment]
Thanks for the confirmation.
Please let us know if this is in your roadmap.
