### ISSUE TITLE
Support for Golang version 1.17 

### ISSUE THREAD

**Issue by RamuRChenchaiah** [gaia-pipeline/gaia#309]
Hi There

To our understanding the supported GoLang version is 1.14
Is there any plan for 1.17 support ?
Please advice

Thank you

**Comment by Skarlso** [comment]
Hi! 

Technically, the support is ` image: circleci/golang:1.16` 1.16. The go mod file could be updated though, for sure. :)

**Comment by RamuRChenchaiah** [comment]
The reason for the request is:
We have vulnerable packages that needs upgrade,which require v1.17

When we try to use the upgraded code, the pipeline fails to complete the setup.

**Comment by Skarlso** [comment]
Ah, I see. I think there would be no problem in updating to 1.17 maybe. 🤔

**Comment by RamuRChenchaiah** [comment]
Thank you so much, @Skarlso for the quicker response.  
This means, we will have a custom image with 1.16/1.17 & use this further?

Hope this does not cause any issues in runtime for the pipeline.

**Comment by Skarlso** [comment]
Well, it's not that easy, but I'll try to update the images later on.

**Comment by RamuRChenchaiah** [comment]
Thank you, @Skarlso

**Comment by Skarlso** [comment]
Going to do a release soon. After that, things hopefully, should be okay.

**Comment by Skarlso** [comment]
Release is done. Feel free to use the new images and version 0.2.9. :)

If any issues arise, please feel free to re-open this issue.
