### ISSUE TITLE
The loading time for all peiplines in dashboard page is high

### ISSUE THREAD

**Issue by RamuRChenchaiah** [gaia-pipeline/gaia#314]
Hi There
A quick context:
1. we have around 9 pipelines. The dashboard page or the settings page takes around 30secs to load the details. Same behaviour when we click on a pipeline.
2. we have upgraded the vm to 4vCPU/8GB RAM from 2vCPU/4GB RAM, but the response is same.

Any thoughts on how to solve this please?

Thank  you.

**Comment by Skarlso** [comment]
I have 11 pipelines, they load instantly. 

Do you have any more data on the pipelines? How many jobs, settings, etc?

**Comment by RamuRChenchaiah** [comment]
Thank you @Skarlso 

Please find below details:
We have at an average 10 jobs per pipeline.
I have also verified that the ulimit is set to unlimited for all users.

**Comment by Skarlso** [comment]
I mean, do they have some special attributes? Like, there are a gazillion steps in them or many settings perhaps?

**Comment by RamuRChenchaiah** [comment]
Nope,not that many steps :) 
These jobs have less data to handle too.

**Comment by Skarlso** [comment]
Super weird. I'll try to recreate some more. What browser are you using? I'm using chrome.

**Comment by RamuRChenchaiah** [comment]
Please note that we use Firefox 97.0 (64-bit) MacOS Monterey 12.1
Thanks

**Comment by Skarlso** [comment]
@RamuRChenchaiah So I tested this on various pipelines and with firefox and chrome and my deployment is loading fine.

Can you please check here:  https://gaia.cronohub.org user `test` password `password123`. And see how fast it loads?

**Comment by Skarlso** [comment]
Please ping me when you can check it. I disabled the user in the meantime. :)
