### ISSUE TITLE
Abiltiy to set configuration flags via environment variables

### ISSUE THREAD

**Issue by rmb938** [gaia-pipeline/gaia#32]
When deploying gaia it would be nice to be able to set the configuration flags via environment variables. 

For ease of development it may be useful to use a cli/configuration system like https://github.com/spf13/viper or https://github.com/alecthomas/kingpin

**Comment by michelvocks** [comment]
We also need to have a look at the configuration in general. I think we will get more configuration parameters in the future and passing in parameters will be unmanageable. :skull:

Not quite sure but do you know what other big open source projects use?

**Comment by rmb938** [comment]
I typically see viper being used in other projects, it can do cli flags, env vars and config files. 

I don't know ifhaving tons of cli flags is a bad thing though. Just look at docker and kubernetes, mostly everyone is fine with having tons of flags.

**Comment by michelvocks** [comment]
This looks actually really good. It's simple and self-explained. I think we can just use it and when we need to do modifications we fork it. What do you think @Skarlso ?

**Comment by Skarlso** [comment]
@rmb938 Implemented. Hopefully that fits the desired need, without also having a major impact code wise.

**Comment by rmb938** [comment]
Yup looks good. Thanks :D
