### ISSUE TITLE
Issue running robot code 

### ISSUE THREAD

**Issue by Vishwa1705** [gaia-pipeline/gaia#328]
Hi there, 

While running robot code in local, chromedriver runs all good, but in pipeline it's complaining that local connections are only allowed.

Wondering what might be the issue. 
If you have any idea, pls share. 

Thanks.

**Comment by Skarlso** [comment]
Hi.

What robot code are you referring to? 🤔

**Comment by Vishwa1705** [comment]
The program is actually written using robot framework ( python ). 

It is supposed to open chrome and do some automated tasks when triggered. 

In local, it doesn't throw any error. But when i create pipeline and try to run it, chrome web driver says "only local connections are allowed"

Also the chrome web driver occupying the port (9515) is refusing to terminate. 


Sorry for my bad grammer, I'm actually trying out pipeline for first time. Thanks.

**Comment by Skarlso** [comment]
Np. Are you using a headless browser? The pipeline runs in a container. Therefor, it doesn't really have access to a browser or some such.

**Comment by Vishwa1705** [comment]
Yes, It's using headless mode.

We also have installed chrome and chromedriver in the container.

It is going to use the chrome driver and launch chrome in headless mode to execute those automated tasks. 

But chromedriver is complaining that only local ports are allowed instead of remote.

Thanks.

**Comment by Skarlso** [comment]
So, I worked with chromedriver AGES ago, but I remember that that particular error message is not an exact error message. It's just a warning if I recall, and maybe the actual error is deeper in the logs?

But also, it might be actually working? Or does it fail immediately?

**Comment by Vishwa1705** [comment]
Apart from the warning, the reason why chromedriver is failing to launch is because pip is occupying the port (9515) on which driver is supposed to run. 

Thanks.

**Comment by Skarlso** [comment]
Nice, so.... When you are launching the driver, set it to look for a different port.

**Comment by Vishwa1705** [comment]
Yes, trying that out. Will update shortly. 

Thanks for your quick response.

Have a great day.

**Comment by Skarlso** [comment]
Nice, good luck! :)
