### ISSUE TITLE
stdin and stdout support with virtual console

### ISSUE THREAD

**Issue by udnaan** [gaia-pipeline/gaia#33]
Not sure if this is considered or is part of the featureset that you want to support.
In my experience, in real systems, it's often unrealistic to except existing software to be modified or rewritten to be made compatible with a pipeline. 

Perhaps such support can be added as a plugin or a pipeline wrapper.

Overall, it is just an idle query since it is still alpha software.

**Comment by michelvocks** [comment]
Welcome @udnaan 🤗 
I'm not quite if I understand your question at all. :disappointed_relieved:
Could you please explain a bit in detail what do you mean?

**Comment by udnaan** [comment]
Let me look into it further before I make a fool of myself. My initial understanding was that you need to add explicit support to each step in the pipeline. I'll reopen if that turns out to be the case.
