### ISSUE TITLE
Architecture documentation

### ISSUE THREAD

**Issue by camerondavison** [gaia-pipeline/gaia#36]
I was wanting to know more about how Gaia runs, is there anything that explains where state is saved, or if it is HA or has plans to be. I didn't see any links to some more info on where credentials for checking out git repos are saved and such. I like all the readme links that do exist but if there is link to further operation instructions I guess I missed it. 

Thanks, sounds like a promising project.

**Comment by michelvocks** [comment]
Welcome @camerondavison 🤗 Thanks for your nice words!

You are absolutely right. We got basically no documentation and that is the part where I'm currently working on. I've just published today our new docs website https://docs.gaia-pipeline.io. 
There is still a lot missing like how to operate Gaia and if it's HA etc...
I hope that we can fix that soon 🤗

So for now, I hope I can answer a few of your questions. Gaia uses currently [bbolt](https://github.com/coreos/bbolt) as storage solution. It is basically a key/value store where all data is saved locally on space as one file. Gaia does not support HA currently but hopefully in the future. 😄 
Credentials for the git repository are also stored in this "database".

**Comment by camerondavison** [comment]
Cool glad it is working in progress. I think just labeling things that are work in progress in the docs is good for people to know if there is an aim to solve it or not. Thanks for the quick update. Just as an FYI we use vault for secrets so it would probably be nice to allow for something like that to be configured either talking directly to a secret manager or in a flat for instead of in a database
