### ISSUE TITLE
Better description in README file

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#43]
I heard from a lot of people that the description (README file) is not very clear. Especially the term "pipeline" led to confusion. We should improve this soon to make clear what Gaia is and maybe how is it comparable to other projects (competitors).

**Comment by issmirnov** [comment]
A good addition would be a clear explanation of what problems this is solving. I read the README and the Tutorials and still don't understand what need this fulfills. Is this a deployment tool? Orchestration? Fancy build tool or glorified scripting language? Etc.
