### ISSUE TITLE
Refactor Git module to use a Storer

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#44]
Right now, the git module can only be tested via actually cloning stuff.

I would like to avoid that, but my current PR is convoluted enough. :) I'm going to do that refactoring with in the confines of this ticket.

**Comment by michelvocks** [comment]
What's bad about cloning stuff? 😄 
I mean, that's the real use-case and we can easily test it. What are the disadvantages in your opinion? 🤗

**Comment by Skarlso** [comment]
Generally it's frowned upon if you poll github a lot and Gods know they need a break. :-) we need end to end tests don't get me wrong. One or more but this scenario needs a push. Which means everytime someone runs this it will pull and push into a repo which is bad. We could mske this test with a switch to only run in Ci but better would be if all it would do is do it in memory.

**Comment by Skarlso** [comment]
This is just like the store needs to be an interface in order to test stuff at the unit level instead of using a really bolt db. And have some end to end tests that actually use bolt db. :-)

**Comment by michelvocks** [comment]
Well. I know from other big projects they are also pulling something (docker images, files from servers etc.) and a git clone is basically the same. We are downloading files from a server. I don't know if github has some kind of DDoS protection which will, at some point, lock you out but I'm pretty sure you will never hit that locally. 😄 

Why do we need a push test? We do not provide any push functionality.

**Comment by Skarlso** [comment]
Ah so that I can test the pull on repo change functionality of the update pipeline on code change feature. :-)

Well, just because other people do it doesn't mean Gaia has to do it. :-)

Generally I think that a unit test is a test where your have full control over all the moving parts. An integration test is where you have a third party of any kind. Generally what I don't want is a test failing because github happens to not be available or throttling us. An integration test is fine frol failing that way. But not a unit test. A unit test should run without Internet in the extremes.

**Comment by michelvocks** [comment]
Alright, good point. Didn't thought about the pull on repo change test. 😄

**Comment by Skarlso** [comment]
Fair enough, it's a new feature after all. :) 👍 Thanks. :)

**Comment by Skarlso** [comment]
This might not be an issue any longer as I found a way to nicely get around the github interface. I can do the same with git as well.

**Comment by Skarlso** [comment]
In test:

https://github.com/gaia-pipeline/gaia/blob/master/pipeline/git_test.go#L252

Using this pattern to mock out a certain part of an API by wrapping it into an interface:

https://github.com/gaia-pipeline/gaia/blob/master/pipeline/git.go#L168-L194
