### ISSUE TITLE
[Feature Request] Distributed execution

### ISSUE THREAD

**Issue by vosmith** [gaia-pipeline/gaia#46]
Do you have plans to use turn Gaia into a Master <-> Worker system where jobs can be run on remote servers?

**Comment by michelvocks** [comment]
Welcome @vosmith 🤗 
Yes, this feature is planned. Sadly, I cannot tell you when we are going to implement this. 
Our feature list is long and there are other features more important than this. 😄

**Comment by michelvocks** [comment]
Now supported via #166
