### ISSUE TITLE
[Proposal] remove strings.Builder in test cases

### ISSUE THREAD

**Issue by vosmith** [gaia-pipeline/gaia#47]
The use of `strings.Builder` requires Go 1.10+.  Since this is only used in the test cases, it leaves an interesting situation where I'm able to run Gaia on Go 1.9, but while developing the tests fail.  I think replacing the strings.Builder, which only serves as an `io.Writer` for the logging would normalize the dev/test/prod environments.

Alternatively an update to the README under the Contributing section could clear this up.

Thoughts?

**Comment by Skarlso** [comment]
Good point!! 

I'll fix that up and use `buf := new(bytes.Buffer)` instead which does the same thing. Sorry for the inconvenience.

**Comment by Skarlso** [comment]
@vosmith Done. Should be okay after merge. Thanks for reporting it. :)

**Comment by michelvocks** [comment]
Good point @vosmith 🤗 

We still have the issue open with the developer guide: #13 
I hope that we can tackle that soon.
