### ISSUE TITLE
Secret store for passwords, tokens, api keys and more

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#51]
We need a secure way to store passwords, tokens, api keys and everything that should be kept secret.
For example when the user wants to access vault via a pipeline. Usually a token is required to get access to vault and this token should be stored in the secret store. 

After a secret has been stored, it must be possible to automatically inject this password during runtime in the pipeline as a job argument. This is not a problem at all, we just have to decide how the user can setup the relationship between a secret and a pipeline. That means, which secret should be available in which pipeline. 

First option: In the details page create a new view to configure the pipeline. Add a subview to manage secrets.

Second and preferred option: Create a new view below settings. This view is for managing secrets. When a view is created or modified it can be linked to multiple pipelines. This has the advantage that one secret can be shared with multiple pipelines.

What do you think?

**Comment by michelvocks** [comment]
ping @Skarlso

**Comment by Skarlso** [comment]
Picking this up.

**Comment by michelvocks** [comment]
Fixed by #56
