### ISSUE TITLE
it show format error when I start piplines

### ISSUE THREAD

**Issue by LaughingXY** [gaia-pipeline/gaia#59]
the error like this  "fork/exec /data/pipelines/test1_golang: exec format error"，how can I resolve this error?Thanks

**Comment by Skarlso** [comment]
Hi @LaughingXY.

Need a bit more information on this. Does your code compile otherwise? How did you create the pipeline? Did you just put in the binary, or did you for something? Where and when are you getting this error? 

Thanks.

**Comment by michelvocks** [comment]
Hey @LaughingXY. 🤗 

Like @Skarlso already said, your pipeline code would help a lot here so that we can try to reproduce your problem. 😄

**Comment by Skarlso** [comment]
Please reopen, if the issue still remains.
