### ISSUE TITLE
Consider not committing in the vendor folder

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#7]
Hi.

I'm trying to start contributing to this project and committing the vendor folder isn't a great way to start things off because they collide most of the time.

That's why the dep Lock file is there. When you start developing, you basically check out the project and go `dep ensure`. The lock file will make sure that all the right versions of the packages are used.

I can understand the committing vendor seems like a good idea because then you'll have the right code always with you, but makes for a poor developer experience.

Feel free to ignore this if you think otherwise, it's fine. :)

**Comment by michelvocks** [comment]
Welcome @Skarlso! Really happy that you decided to contribute. This means a lot to me. 😇

You are right and I'm still unsure if committing the vendor folder was the right decision.
I looked up several other big projects (for example kubernetes and docker) and they all committed the vendor folder. That is the reason why I did it.

I'm not sure if they also have the same problems?

**Comment by Skarlso** [comment]
eh /shrug. It depends. That's why I'm saying feel free to ignore it. I guess it doesn't matter that much..

Dep has this to say about it:

https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

> It's up to you:

> Pros

> It's the only way to get truly reproducible builds, as it guards against upstream renames, deletes and > commit history overwrites.
> You don't need an extra dep ensure step to sync vendor/ with Gopkg.lock after most operations, > such as go get, cloning, getting latest, merging, etc.

> Cons

> Your repo will be bigger, potentially a lot bigger, though prune can help minimize this problem.
> PR diffs will include changes for files under vendor/ when Gopkg.lock is modified, however files in >vendor/ are hidden by default on GitHub.

So, it's really up to you. :)

Also, Hi! :)
