### ISSUE TITLE
Fix scale of pipeline views in overview on large screens

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#73]
![screen shot 2018-08-12 at 13 00 06](https://user-images.githubusercontent.com/2463119/44001305-bc52c55a-9e2f-11e8-8a80-2f3b5aa1c376.png)

On large screens, there is too much space between multiple pipelines.

**Comment by speza** [comment]
Thought I'd quickly give this one a fix. Few little tweaks but seems much better locally for me - 
![capture 2018-10-16 at 17 45 30](https://user-images.githubusercontent.com/5376774/47033057-cadd3280-d16b-11e8-8e87-147b75722ec2.png)
