### ISSUE TITLE
Remove tabs-panel from vault view

### ISSUE THREAD

**Issue by michelvocks** [gaia-pipeline/gaia#76]
![screen shot 2018-08-12 at 13 09 25](https://user-images.githubusercontent.com/2463119/44001363-078858e0-9e31-11e8-9fc7-cfbb2fff141a.png)

We use the tabs-view for vault but I don't see any reason to do that. WDYT @Skarlso ?

**Comment by Skarlso** [comment]
What's tabs-view? 🤣

**Comment by michelvocks** [comment]
The thing with "Manage Secrets" 😄 It's a tabs-panel (multiple views in one)
