### ISSUE TITLE
cannot copy compiled binary: no such file or directory

### ISSUE THREAD

**Issue by Phil-Taylor-IW** [gaia-pipeline/gaia#99]
Hi there, I love the concept of Gaia and am trying out the demos in your tutorials but am getting this error:

```cannot copy compiled binary: open /data/pipelines/gaia-pipeline/go-example_golang: no such file or directory```

I'm not that familiar with Go but it appears the repos are being cloned and the code compiled in `./tmp/golang/src/495c7f71-d409-4933-a175-534fe8c066df/gaia-pipeline//go-example_golang` but not copied to the correct place however if I manually copy to `./pipelines`, I get a Success message.

I guess that's weird too since the error message implies `./data/pipelines` - will take a look at the source but am no coder.

![image](https://user-images.githubusercontent.com/42429032/44877445-1e004080-acf8-11e8-9f6f-8c5a9f8483b3.png)

![image](https://user-images.githubusercontent.com/42429032/44877679-cca48100-acf8-11e8-8200-3b0086b33dd7.png)

I'm on a MacBook Pro running 10.13.6 and Docker 18.06.1-ce

Cheers, Phil

**Comment by Skarlso** [comment]
First off, hi @Phil-Taylor-IW! Welcome, and thanks for reporting this issue. I'll look into it as soon as I can! :)

**Comment by Skarlso** [comment]
So, could you tell me a little bit more what exactly were you trying to do? 

For me, I was pressing, create pipeline and I'm using the example repository (https://github.com/gaia-pipeline/go-example).

This is the result of me creating the pipeline: 

<img width="565" alt="screen shot 2018-08-31 at 06 55 07" src="https://user-images.githubusercontent.com/182850/44893349-f0f96100-acea-11e8-8384-57f977804a0a.png">

And then running the pipeline which also worked fine:

<img width="1238" alt="screen shot 2018-08-31 at 06 55 42" src="https://user-images.githubusercontent.com/182850/44893352-f8206f00-acea-11e8-874b-182bb77de43f.png">

I'm also on a mac.

**Comment by Phil-Taylor-IW** [comment]
That's all I was doing, I ran the container, logged in, created a user and added my Github creds but didn't have any code so created a new pipeline just as you did there. Let me kill my repo and start again from scratch.

**Comment by Phil-Taylor-IW** [comment]
Cool - that seemed to do it! I must have had some bad config hanging about. Thanks for that!

![image](https://user-images.githubusercontent.com/42429032/44893730-7f4c0200-ad40-11e8-9551-c5276198223c.png)

**Comment by Skarlso** [comment]
Yay! :)

**Comment by Phil-Taylor-IW** [comment]
Totally loving the gaia concept. Is anyone working on a Ballerina SDK? That would be of great interest.

**Comment by Skarlso** [comment]
@Phil-Taylor-IW I don't think so, no. There are quiet many features that we need to implement first, like distributed execution which is on my plate right now. Also, other things that you see in the issues section. :) But we are always happy if people jump in on the fun though. :)

**Comment by Phil-Taylor-IW** [comment]
I saw Rust mentioned and wasn’t suggesting you do it ;-)

I’m not a coder but am trying to sell the idea internally.

Win-win.

**Comment by Skarlso** [comment]
@Phil-Taylor-IW Yeah, as an issue for a reminder that it would be cool to have. :) Although, apparently the gRPC for rust isn't maintained. :/ So I'm not sure if I ever get a chance to do it. 

Otherwise, yeah, if you wish Gaia would do something that you would like to see, feel free to create an issue so we never forget about it. :)

**Comment by Phil-Taylor-IW** [comment]
Actually I don't care about Rust but work for an integration company and would like to see a Ballerina SDK. It[ looks like it has gRPC support](https://ballerina.io/learn/by-guide/grpc-service/) so I will create an Issue for this soon thanks.
